### ISSUE TITLE
rpy2 installation through pip failing

### ISSUE THREAD

**Issue by SabineBellstedt** [swincas/cookies-n-code#15]
I have yet another issue with a python package installation! This one is about the package `rpy2`, which interfaced between `R` and `python`. I have this installed just fine on my desktop, but I've been having difficulty installing it for a long time on my laptop. Thanks to the fact that I'm still using `python 2`, I need to install an older version of the package. When I do so (either by using `pip`, or when downloading and installing it manually), I get the following error:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py", line 441, in <module>
        [os.path.join('doc', 'source', 'rpy2_logo.png')])],
      File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 280, in run
        self.find_sources()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 295, in find_sources
        mm.run()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 526, in run
        self.add_defaults()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py", line 152, in finalize_options
        config += get_rconfig(r_home, about)
      File "/private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py", line 312, in get_rconfig
        rc = RConfig.from_string(rconfig, allow_empty = allow_empty)
      File "/private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py", line 272, in from_string
        + '\nin string\n' + string)
    ValueError: Invalid substring
    -fopenmp
    in string
    -fopenmp -L/usr/local/lib -F/Library/Frameworks/R.framework/.. -framework R -lpcre -llzma -lbz2 -lz -licucore -lm -liconv
```

I originally thought this could be some issue with the `xcode` installation, but after some checking I think that's all up-to-date. Any ideas??

**Comment by manodeep** [comment]
Can you just post the entire output of `cat -n /private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py`

**Comment by SabineBellstedt** [comment]
Apparently not very helpful:
```
HAW121360:rpy2-2.2.1 sbellstedt$ cat -n /private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py
cat: /private/var/folders/7d/8zmh9zyj6d7_yc4sgd5y59_hxn3yk1/T/pip-build-sE9iOi/rpy2/setup.py: No such file or directory
```

Is it just the actual code of `setup.py` that I'm installing from that you want to see?

**Comment by SabineBellstedt** [comment]
Here are the file contents:

```
import os, os.path, sys, shutil, re, itertools
from collections import namedtuple
from distutils.command.build_ext import build_ext as _build_ext
from distutils.command.build import build as _build

from distutils.core import setup
from distutils.core import Extension

pack_name = 'rpy2'
pack_version = __import__('rpy').__version__

package_prefix='.'
if sys.version_info >= (3,):
    print("Using 2to3 to translate Python2-only idioms into Python3 code. Please wait...")
    # Python 3 and we need to translate code
    package_prefix = os.path.join('build', 'python3_rpy')
    from distutils import filelist, dir_util, file_util, util#, log
    #log.set_verbosity(1)
    fl = filelist.FileList()
    tmp = open("MANIFEST.in")
    for line in tmp:
        line = line.rstrip()
        if line != '':
            fl.process_template_line(line)
    tmp.close()
    dir_util.create_tree(package_prefix, fl.files)
    outfiles_2to3 = []
    #dist_script = os.path.join("build", "src", "distribute_setup.py")
    for f in fl.files:
        outf, copied = file_util.copy_file(f, os.path.join(package_prefix, f), 
                                           update=1)
        if copied and outf.endswith(".py"): #and outf != dist_script:
            outfiles_2to3.append(outf)
        if copied and outf.endswith('api_tests.txt'):
            # XXX support this in distutils as well
            from lib2to3.main import main
            main('lib2to3.fixes', ['-wd', os.path.join(package_prefix, 
                                                       'tests', 'api_tests.txt')])

    util.run_2to3(outfiles_2to3)

    # arrange setup to use the copy
    sys.path.insert(0, package_prefix)
    src_root = package_prefix
    print('done.')
else:
    from distutils.core import setup    
from distutils.core import Extension


class build(_build):
    user_options = _build.user_options + \
        [
        #('r-autoconfig', None,
        # "guess all configuration paths from " +\
        #     "the R executable found in the PATH " +\
        #     "(this overrides r-home)"),
        ('r-home=', None, 
         "full path for the R home to compile against " +\
             "(see r-autoconfig for an automatic configuration)"),
        ('r-home-lib=', None,
         "full path for the R shared lib/ directory " +\
             "(<r-home>/lib otherwise)"),
        ('r-home-modules=', None,
         "full path for the R shared modules/ directory " +\
             "(<r-home>/modules otherwise)") 
        ]
    boolean_options = _build.boolean_options #+ \
        #['r-autoconfig', ]


    def initialize_options(self):
        _build.initialize_options(self)
        self.r_autoconfig = None
        self.r_home = None
        self.r_home_lib = None
        self.r_home_modules = None

class build_ext(_build_ext):
    """
    -DRPY_STRNDUP          : definition of strndup()
    -DRPY_VERBOSE
    -DRPY_DEBUG_PRESERV
    -DRPY_DEBUG_PROMISE    : evaluation of promises
    -DRPY_DEBUG_OBJECTINIT : initialization of PySexpObject
    -DRPY_DEBUG_CONSOLE    : console I/O
    -DRPY_DEBUG_COBJECT    : SexpObject passed as a CObject
    -DRPY_DEBUG_GRDEV
    """
    user_options = _build_ext.user_options + \
        [
        #('r-autoconfig', None,
        #  "guess all configuration paths from " +\
        #      "the R executable found in the PATH " +\
        #      "(this overrides r-home)"),
        ('r-home=', None, 
         "full path for the R home to compile against " +\
             "(see r-autoconfig for an automatic configuration)"),
        ('r-home-lib=', None,
         "full path for the R shared lib/ directory" +\
             "(<r-home>/lib otherwise)"),
        ('r-home-modules=', None,
         "full path for the R shared modules/ directory" +\
             "(<r-home>/modules otherwise)")]

    boolean_options = _build_ext.boolean_options #+ \
        #['r-autoconfig', ]

    def initialize_options(self):
        _build_ext.initialize_options(self)
        self.r_autoconfig = None
        self.r_home = None
        self.r_home_lib = None
        self.r_home_modules = None

    def finalize_options(self):
        self.set_undefined_options('build',
                                   #('r_autoconfig', 'r_autoconfig'),
                                   ('r_home', 'r_home'))
        _build_ext.finalize_options(self) 
        if self.r_home is None:
            tmp = os.popen("R RHOME")
            self.r_home = tmp.readlines()
            tmp.close()
            if len(self.r_home) == 0:
                raise SystemExit("Error: Tried to guess R's HOME but no R command in the PATH.")

    #Twist if 'R RHOME' spits out a warning
            if self.r_home[0].startswith("WARNING"):
                self.r_home = self.r_home[1]
            else:
                self.r_home = self.r_home[0]
            #self.r_home = [self.r_home, ]

        if self.r_home is None:
            raise SystemExit("Error: --r-home not specified.")
        else:
            self.r_home = self.r_home.split(os.pathsep)

        rversions = []
        for r_home in self.r_home:
            r_home = r_home.strip()
        rversion = get_rversion(r_home)
        if cmp_version(rversion[:2], [2, 8]) == -1:
            raise SystemExit("Error: R >= 2.8 required.")
        rversions.append(rversion)

        config = RConfig()
        for about in ('--ldflags', '--cppflags', 
                      'LAPACK_LIBS', 'BLAS_LIBS'):
            config += get_rconfig(r_home, about)

        print(config.__repr__())

        self.include_dirs.extend(config._include_dirs)
        self.libraries.extend(config._libraries)
        self.library_dirs.extend(config._library_dirs)

        if self.r_home_modules is None:
            self.library_dirs.extend([os.path.join(r_home, 'modules'), ])
        else:
            self.library_dirs.extends([self.r_home_modules, ])

        #for e in self.extensions:
        #    self.extra_link_args.extra_link_args(config.extra_link_args)
        #    e.extra_compile_args.extend(extra_link_args)

    def run(self):
        _build_ext.run(self)



def get_rversion(r_home):
    r_exec = os.path.join(r_home, 'bin', 'R')
    # Twist if Win32
    if sys.platform == "win32":
        rp = os.popen3('"'+r_exec+'" --version')[2]
    else:
        rp = os.popen('"'+r_exec+'" --version')
    rversion = rp.readline()
    #Twist if 'R RHOME' spits out a warning
    if rversion.startswith("WARNING"):
        rversion = rp.readline()
    m = re.match('^R version ([^ ]+) .+$', rversion)
    rversion = m.groups()[0]
    rversion = rversion.split('.')
    rversion[0] = int(rversion[0])
    rversion[1] = int(rversion[1])
    rp.close()
    return rversion

def cmp_version(x, y):
    if (x[0] < y[0]):
        return -1
    if (x[0] > y[0]):
        return 1
    if (x[0] == y[0]):
        if len(x) == 1 or len(y) == 1:
            return 0
        return cmp_version(x[1:], y[1:])

class RConfig(object):
    _include_dirs = None
    _libraries = None
    _library_dirs = None 
    _extra_link_args = None
    _frameworks = None
    _framework_dirs = None

    def __init__(self,
                 include_dirs = tuple(), libraries = tuple(),
                 library_dirs = tuple(), extra_link_args = tuple(),
                 frameworks = tuple(),
                 framework_dirs = tuple()):
        for k in ('include_dirs', 'libraries', 
                  'library_dirs', 'extra_link_args'):
            v = locals()[k]
            if not isinstance(v, tuple):
                if isinstance(v, str):
                    v = [v, ]
            v = tuple(set(v))
            self.__dict__['_'+k] = v
        # frameworks are specific to OSX
        for k in ('framework_dirs', 'frameworks'):
            v = locals()[k]
            if not isinstance(v, tuple):
                if isinstance(v, str):
                    v = [v, ]
            v = tuple(set(v))
            self.__dict__['_'+k] = v
            self.__dict__['_'+'extra_link_args'] = tuple(set(v + self.__dict__['_'+'extra_link_args']))

    @staticmethod
    def from_string(string, allow_empty = False):
        possible_patterns = ('^-L(?P<library_dirs>[^ ]+)$',
                             '^-l(?P<libraries>[^ ]+)$',
                             '^-I(?P<include_dirs>[^ ]+)$',
                             '^(?P<framework_dirs>-F[^ ]+?)$',
                             '^(?P<frameworks>-framework [^ ]+)$',
                             '^(?P<extra_link_args>-Wl[^ ]+)$')
        pp = [re.compile(x) for x in possible_patterns]
        # sanity check of what is returned into rconfig
        rconfig_m = None        
        span = (0, 0)
        rc = RConfig()
        
        for substring in re.split('(?<!-framework) ', string):
            ok = False
            for pattern in pp:
                rconfig_m = pattern.match(substring)
                if rconfig_m is not None:
                    rc += RConfig(**rconfig_m.groupdict())
                    span = rconfig_m.span()
                    ok = True
                    break
                elif rconfig_m is None:
                    if allow_empty and (rconfig == ''):
                        print(cmd + '\nreturned an empty string.\n')
                        rc += RConfig()
                        ok = True
                        break
                    else:
                        # if the configuration points to an existing library, 
                        # use it
                        if os.path.exists(string):
                            rc += RConfig(library = substring)
                            ok = True
                            break
            if not ok:
                raise ValueError('Invalid substring\n' + substring 
                                 + '\nin string\n' + string)
        return rc
            
    def __repr__(self):
        s = 'Configuration for R as a library:' + os.linesep
        s += os.linesep.join(
            ['  ' + x + ': ' + self.__dict__['_'+x].__repr__() \
                 for x in ('include_dirs', 'libraries',
                           'library_dirs', 'extra_link_args')])
        s += os.linesep + ' # OSX-specific (included in extra_link_args)' + os.linesep 
        s += os.linesep.join(
            ['  ' + x + ': ' + self.__dict__['_'+x].__repr__() \
                 for x in ('framework_dirs', 'frameworks')]
            )
        
        return s

    def __add__(self, config):
        assert isinstance(config, RConfig)
        res = RConfig(include_dirs = self._include_dirs + \
                          config._include_dirs,
                      libraries = self._libraries + config._libraries,
                      library_dirs = self._library_dirs + \
                          config._library_dirs,
                      extra_link_args = self._extra_link_args + \
                          config._extra_link_args,
                      frameworks = self._frameworks + config._frameworks,
                      framework_dirs = self._framework_dirs + config._framework_dirs)
        return res


def get_rconfig(r_home, about, allow_empty = False):
    r_exec = os.path.join(r_home, 'bin', 'R')
    cmd = '"'+r_exec+'" CMD config '+about
    rp = os.popen(cmd)
    rconfig = rp.readline()
    #Twist if 'R RHOME' spits out a warning
    if rconfig.startswith("WARNING"):
        rconfig = rp.readline()
    rconfig = rconfig.strip()
    rc = RConfig.from_string(rconfig, allow_empty = allow_empty)
    rp.close()
    return rc

def getRinterface_ext():
    #r_libs = [os.path.join(RHOME, 'lib'), os.path.join(RHOME, 'modules')]
    r_libs = []
    extra_link_args = []

    #FIXME: crude way (will break in many cases)
    #check how to get how to have a configure step
    define_macros = []

    if sys.platform == 'win32':
        define_macros.append(('Win32', 1))
    else:
        define_macros.append(('R_INTERFACE_PTRS', 1))
        define_macros.append(('HAVE_POSIX_SIGJMP', 1))

    define_macros.append(('CSTACK_DEFNS', 1))
    define_macros.append(('RIF_HAS_RSIGHAND', 1))


    if sys.byteorder == 'big':
        define_macros.append(('RPY_BIGENDIAN', 1))
    else:
        pass


    include_dirs = []
    
    rinterface_ext = Extension(
            name = pack_name + '.rinterface._rinterface',
            sources = [ \
            #os.path.join('rpy', 'rinterface', 'embeddedr.c'), 
            #os.path.join('rpy', 'rinterface', 'r_utils.c'),
            #os.path.join('rpy', 'rinterface', 'buffer.c'),
            #os.path.join('rpy', 'rinterface', 'sequence.c'),
            #os.path.join('rpy', 'rinterface', 'sexp.c'),
            os.path.join(package_prefix,
                         'rpy', 'rinterface', '_rinterface.c')
                       ],
            depends = [os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'embeddedr.h'), 
                       os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'r_utils.h'),
                       os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'buffer.h'),
                       os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'sequence.h'),
                       os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'sexp.h'),
                       os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'rpy_rinterface.h'),
                       os.path.join(package_prefix,
                                    'rpy', 'rinterface', 'rpy_device.h')
                       ],
            include_dirs = [os.path.join(package_prefix,
                                         'rpy', 'rinterface'),] + include_dirs,
            libraries = ['R', ],
            library_dirs = r_libs,
            define_macros = define_macros,
            runtime_library_dirs = r_libs,
            #extra_compile_args=['-O0', '-g'],
            #extra_link_args = extra_link_args
            )

    rpy_device_ext = Extension(
        pack_name + '.rinterface.rpy_device',
            [
            os.path.join('rpy', 'rinterface', 'rpy_device.c'),
             ],
            include_dirs = include_dirs + 
                            [os.path.join('rpy', 'rinterface'), ],
            libraries = ['R', ],
            library_dirs = r_libs,
            define_macros = define_macros,
            runtime_library_dirs = r_libs,
            #extra_compile_args=['-O0', '-g'],
            extra_link_args = extra_link_args
        )

    return [rinterface_ext, rpy_device_ext]

if __name__ == '__main__':
    rinterface_exts = []
    ri_ext = getRinterface_ext()
    rinterface_exts.append(ri_ext)

    pack_dir = {pack_name: os.path.join(package_prefix, 'rpy')}

    import distutils.command.install
    for scheme in distutils.command.install.INSTALL_SCHEMES.values():
        scheme['data'] = scheme['purelib']

    setup(
        #install_requires=['distribute'],
        cmdclass = {'build': build,
                    'build_ext': build_ext},
        name = pack_name,
        version = pack_version,
        description = "Python interface to the R language",
        url = "http://rpy.sourceforge.net",
        license = "AGPLv3.0 (except rpy2.rinterface: LGPL)",
        author = "Laurent Gautier",
        author_email = "lgautier@gmail.com",
        ext_modules = rinterface_exts[0],
        package_dir = pack_dir,
        packages = [pack_name,
                    pack_name + '.rlike',
                    pack_name + '.rlike.tests',
                    pack_name + '.rinterface',
                    pack_name + '.rinterface.tests',
                    pack_name + '.robjects',
                    pack_name + '.robjects.tests',
                    pack_name + '.robjects.lib',
                    pack_name + '.interactive',
                    pack_name + '.interactive.tests'
                    ],
        classifiers = ['Programming Language :: Python',
                       'Programming Language :: Python :: 2',
                       'Programming Language :: Python :: 3',
                       'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
                       'License :: OSI Approved :: GNU Affero General Public License v3',
                       'Intended Audience :: Developers',
                       'Intended Audience :: Science/Research',
                       'Development Status :: 5 - Production/Stable'
                       ],
        data_files = [(os.path.join('rpy2', 'images'), 
                       [os.path.join('doc', 'source', 'rpy2_logo.png')])],

        #[pack_name + '.rinterface_' + x for x in rinterface_rversions] + \
            #[pack_name + '.rinterface_' + x + '.tests' for x in rinterface_rversions]
        )
```

**Comment by SabineBellstedt** [comment]
Based on poor online advice, I just tried the install with the lines 
```
if not ok:
                raise ValueError('Invalid substring\n' + substring 
                                 + '\nin string\n' + string)
```
 commented out, which did allow for the package to be installed, but when the code needing it was actually called, I got the following warning:

```
/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Segmentation fault: 11
```

**Comment by manodeep** [comment]
I am guessing the `-fopenmp` flag is breaking the regexp matching but not really sure. Do you mind putting in liberal amounts of `print` statements after this line: 
```python
for substring in re.split('(?<!-framework) ', string):
    ok = False
    print(.....)
```

**Comment by SabineBellstedt** [comment]
Okay, so I've asked the code to print out what I deemed to be the most important variables. At the first instance of calling that function, the print output was:
```
pp: [<_sre.SRE_Pattern object at 0x10986ec30>, <_sre.SRE_Pattern object at 0x10986ecf0>, <_sre.SRE_Pattern object at 0x10986edb0>, <_sre.SRE_Pattern object at 0x10986ee70>, <_sre.SRE_Pattern object at 0x10993b030>, <_sre.SRE_Pattern object at 0x1098c70f8>]
rconfig_m: None
allow_empty: False
string: -fopenmp -L/usr/local/lib -F/Library/Frameworks/R.framework/.. -framework R -lpcre -llzma -lbz2 -lz -licucore -lm -liconv
```
and then there were six outputs of the following:
```
rconfig_m: None
allow_empty: False
string: -fopenmp -L/usr/local/lib -F/Library/Frameworks/R.framework/.. -framework R -lpcre -llzma -lbz2 -lz -licucore -lm -liconv
```

**Comment by SabineBellstedt** [comment]
The other thing I noted was that the `rconfig` parameter is undefined by the time the line `if allow_empty and (rconfig == ''):` is called...

**Comment by SabineBellstedt** [comment]
And yes, `os.path.exists(string)` at the end returns `False`, indicating that there is an issue with `-fopenmp`....

**Comment by manodeep** [comment]
Potential different solution -- what happens if you set `allow_empty=True`?

**Comment by SabineBellstedt** [comment]
then it throws an error because `rconfig` hasn't been defined... Then I just removed the `rconfig == ''` check, at which point the doce throws an error because `cmd` hasn't been defined...

**Comment by manodeep** [comment]
Okay, another option -- what happens if you add `'^(-fopenmp)$'` to `possible_patterns`?

Otherwise, do `if substring == '-fopenmp': ok=True`

**Comment by SabineBellstedt** [comment]
In both options,  `rpy2` successfully installs, but again when I try to use it in my existing code it gives me a `segmentation fault`:
```
/Users/sbellstedt/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Segmentation fault: 11
```

**Comment by manodeep** [comment]
What I don't understand is where the `-fopenmp` flag is creeping in -- is that in your `R` binary compilation/link options by any chance? What do you get if you do `echo $CFLAGS`

Another thing to do for the second case is:

```python
if substring == '-fopenmp': 
    rc += RConfig()
    ok=True
```
(although I don't think that will affect anything - this should only affect compiling/linking)

How about running with `python -v`

**Comment by SabineBellstedt** [comment]
Ah, so I just found what was causing the `matplotlib` errors in my other code (It seems to have been caused by a `matplotlib.use('TkAgg')` readin at the start), however the `segmentation fault:11` remains. 

Do you think that's to do with `rpy2`, or something else?

**Comment by SabineBellstedt** [comment]
`echo $CFLAGS` returns nothing...

**Comment by manodeep** [comment]
Can you locate where the `segfault` occurs (with `python -v`) ?

**Comment by SabineBellstedt** [comment]
I just identified this thread in which people have experienced the almost identical problem:
https://bitbucket.org/rpy2/rpy2/issues/214/segmentation-fault-11-on-mac-os-x-mountain

Will see if I can troubeshoot using some of their advice... 
(For the moment, that seems to just be reinstalling R through Anaconda)

**Comment by SabineBellstedt** [comment]
Nope, installing R through Anaconda as a way of matching the python installation didn't remove the error.

**Comment by manodeep** [comment]
Well, time to dig deeper. What are your OSX and Xcode versions?

**Comment by manodeep** [comment]
Another likely candidate is that different `R` versions are being picked up at link time vs run time. Can you paste the entire output from a new `python setup.py install` 

(Basically, try to re-compile the shared library after adding in the following flag `-Xlinker -rpath -Xlinker /path/to/R/library`. That will embed the compile time R library path into the shared library and then there shouldn't be any such mis-matches between link time and run time libraries)

**Comment by SabineBellstedt** [comment]
I'm on OSX 10.12.6. 

I'm not entirely sure about checking the version of my xcode. I don't have the app installed via the App store (OS not recent enough to install), but I have the xcode command line tools, which I assume is an equivalent thing?

**Comment by SabineBellstedt** [comment]
And I'm back to getting errors with my `python setup.py install`:

```
running install
running build
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 446, in <module>
    [os.path.join('doc', 'source', 'rpy2_logo.png')])],
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/sbellstedt/anaconda2/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 152, in finalize_options
    config += get_rconfig(r_home, about)
  File "setup.py", line 317, in get_rconfig
    rc = RConfig.from_string(rconfig, allow_empty = allow_empty)
  File "setup.py", line 277, in from_string
    + '\nin string\n' + string)
ValueError: Invalid substring

in string
```

which is strange, given that all I've done is update R...??

**Comment by manodeep** [comment]
If you open xcode, and then click the "about xcode"  menu option, that should tell you the version. 

So you are on OSX Sierra (the same as me) -- I will try to reproduce your problem. Is it simply installing `rpy2` (I will do `conda install R64 rpy2`...or equivalent)

**Comment by SabineBellstedt** [comment]
Also just figured out how to check the version of xcode command line tools I have installed. It is `xcode-select version 2347`.

**Comment by manodeep** [comment]
Will you please try this:

```bash
#!/bin/bash                                                                                                                                                            
conda create -q --yes -n rpy2_test python=2.7 numpy
conda install -q --yes rpy2
source activate rpy2_test
python -v -c "import rpy2.rinterface"
```
Just tried on mine, and there was no crash.

**Comment by SabineBellstedt** [comment]
It all looked like it was working, but then the final import returned an error:
```
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named rpy2.rinterface
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] encodings
# cleanup[1] site
# cleanup[1] sysconfig
# cleanup[1] abc
# cleanup[1] _weakrefset
# cleanup[1] sre_constants
# cleanup[1] _codecs
# cleanup[1] _warnings
# cleanup[1] zipimport
# cleanup[1] _sysconfigdata
# cleanup[1] encodings.utf_8
# cleanup[1] _osx_support
# cleanup[1] codecs
# cleanup[1] signal
# cleanup[1] traceback
# cleanup[1] posix
# cleanup[1] encodings.aliases
# cleanup[1] exceptions
# cleanup[1] _weakref
# cleanup[1] re
# cleanup[1] _locale
# cleanup[1] sre_compile
# cleanup[1] _sre
# cleanup[1] sre_parse
# cleanup[2] copy_reg
# cleanup[2] posixpath
# cleanup[2] errno
# cleanup[2] _abcoll
# cleanup[2] types
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] warnings
# cleanup[2] UserDict
# cleanup[2] os.path
# cleanup[2] linecache
# cleanup[2] os
# cleanup sys
# cleanup __builtin__
# cleanup ints: 20 unfreed ints
# cleanup floats
```

**Comment by manodeep** [comment]
That's so strange. Did the `conda install rpy2` succeed?

What happens if you open an python/ipython session and just do `import rpy2`

**Comment by SabineBellstedt** [comment]
I seem to be the queen of strange issues when it comes to my installation experiences. 

```
HAW121360:rpy2-2.2.1 sbellstedt$ conda install rpy2
Solving environment: done

# All requested packages already installed.

HAW121360:rpy2-2.2.1 sbellstedt$ python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Sep 21 2017, 17:38:20) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpy2
>>> import rpy2.rinterface
>>> exit()
```

That all seems to be working on its own now! Not entirely sure what changed. 
When running my code now, I'm being informed about all the `R` packages that aren't installed, which makes sense given that I reinstalled `R`. So this kind of makes me think that the problem has been solved..??!! A little bit concerning because if so, then I don't know what fixed it...

**Comment by manodeep** [comment]
Did you figure out what was going on? Otherwise, do you want to write down what solved the issue...

**Comment by manodeep** [comment]
@SabineBellstedt Did this ever get resolved?

**Comment by SabineBellstedt** [comment]
Yes, I did find a solution to this problem in the end. If I make sure that `python` is installed using `conda`, then I was able to install `R` through `conda` as well. At this point, the installation of `rpy2` via the raw installation file (`python install rpy2.py`) was fine. 

So it seems like the issue was just various incompatibilities that needed sorting out...
